server:
  port: 8081
spring:
  profiles:
    active: dev
---

server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: prod


#
#person:
#  lastName: zhangsan
#  age: 55
#  boss: true
#  birth: 1994/08/07
#  maps: {k1: v1,k2: 55}
#  lists:
#   - lisi
#   - zhaowu
#  dog:
#   name: wangshoulin
#   age: 46


